### ISSUE TITLE
The apache logs are not processed

### ISSUE THREAD

**Issue by tshrinivasan** [shanpandya/LogAn#1]
Hi,

I am trying to use this tool.

Setup everything, and using my http log files as input.
saved the logs files in folder named 'data'

running as

python3 LogAn.py data

But getting this error.

'NoneType' object has no attribute 'group'
Line number: 1
127.0.0.1 - - [25/Dec/2018:05:25:00 +0000] "GET / HTTP/1.1" - 342

Except this, no out is received.

Guide me on what I am missing.

**Comment by shanpandya** [comment]
Hi,

The tool was built to only support SSL access files, so does not work for your http log files.

I have added a modified script "LogAnNoSSL" which should work for you. I have not had a chance to conduct extensive testing, but please try this out.

**Comment by tshrinivasan** [comment]
Great. Thanks. Will test and share results.

**Comment by tshrinivasan** [comment]
Hi,

The same issue is still there.
sharing the sample log file, result here.



cat log-1/a.log 
 127.0.0.1 - - [25/Dec/2018:05:25:00 +0000] "GET / HTTP/1.1" - 342

 python3 LogAnNoSSL.py log-1
Found directory: ./log-1
log-1/a.log
'NoneType' object has no attribute 'group'
Skipped line number: 1
 127.0.0.1 - - [25/Dec/2018:05:25:00 +0000] "GET / HTTP/1.1" - 342

0 duplicate lines found (and removed in 'Results_duplicate_lines_removed.txt'


same result for original log files I have.
Please check this.

**Comment by tshrinivasan** [comment]
Can you attach a sample apache log file or few lines of it, so that I can compare with my log files for any missing fields?

**Comment by shanpandya** [comment]
Here's an example of a line from the HTTP logs I'm testing against:
127.0.0.1 - - [26/Jun/2017:06:25:15 +0100] "GET /~xxx/xxx HTTP/1.1" 410 381 "-" "Mozilla/5.0 (compatible; Yahoo! Slurp; http://help.yahoo.com/help/us/ysearch/slurp)"

It seems that "-" for status code was causing an error with your log file. I have just fixed this with an update. It should work OK now if you add fields for the referer and user agent. Have tested and this works fine now:
127.0.0.1 - - [25/Dec/2018:05:25:00 +0000] "GET HTTP/1.1" - 342 "-" "-"

**Comment by tshrinivasan** [comment]
Thanks,

added "-" "-" at the end of each line.

54.252.254.224 - - [26/Nov/2018:05:24:54 +0000] "GET http://localhost:80/
HTTP/1.1" 0 342 "-" "-"
54.245.168.0 - - [26/Nov/2018:05:24:58 +0000] "GET http://localhost:80/
HTTP/1.1" 0 342 "-" "-"
168.235.203.249 - - [26/Nov/2018:05:24:28 +0000] "GET
http://localhost:80/favicon.ico HTTP/1.1" 0 358 "-" "-"
54.241.32.64 - - [26/Nov/2018:05:24:47 +0000] "GET http://localhost:80/
HTTP/1.1" 0 342 "-" "-"
176.34.159.192 - - [26/Nov/2018:05:24:47 +0000] "GET http://localhost:80/
HTTP/1.1" 0 342 "-" "-"

These lines are not processed.

Giving same error as
'NoneType' object has no attribute 'group'
Skipped line number: 5
etc.

What am i missing?

**Comment by shanpandya** [comment]
It's giving an error because the status code in your log lines is "0". This is strange as normally status coes are 3 digits:
https://www.alertsite.com/cgi-bin/helpme.cgi?page=httpstatus.html

I've added support for 0 as a status code which should allow you to use to the tool - have tested against lines above and is working fine.
