### ISSUE TITLE
replace "Setup_files" with "Setup_Files"

### ISSUE THREAD

**Issue by tshrinivasan** [shanpandya/LogAn#2]
grep -n "Setup_files" LogAn.py 

25:parser.read('Setup_files/configuration_file.ini')
524:    with open ("Setup_files/false_positive_XSS_regex.txt", "r") as infile:
540:    with open ("Setup_files/false_positive_SQL_regex.txt", "r") as infile:

replace on these lines. 
For both LogAn.py and LogAnNoSSL.py

**Comment by shanpandya** [comment]
Thanks! Just fixed
